export type dataObjectType = {
    sectorTitle: string,
    sectorDescription: string[],
    jobTitle: string | null,
    jobDescription: string[] | null,
    jobColor: string | null,
    directions: string[] | null,
    profiles: string[] | null,
    vacancies: string | null,
    url: string | null,
}
export type dataType = Record<string, dataObjectType>

const data: dataType = {
    "01-03-04-1": {
        "sectorTitle": "01.03.04 | Прикладная математика",
        "sectorDescription": ["Подготовка по направлению включает изучение современных концепций и методов анализа больших данных с целью выявления закономерностей и зависимостей, прогнозирования тенденций и значений параметров, составления аналитических обзоров и справок, подготовки управленческих решений и материалов бизнес-аналитики."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["01.03.04"],
        "profiles": ["Анализ данных"],
        "vacancies": null,
        "url": null
    },
    "09-03-01-1": {
        "sectorTitle": "09.03.01 | Информатика и вычислительная техника",
        "sectorDescription": ["Направление ориентировано на подготовку профессионалов в широком спектре технологий, связанных с компьютерной и вычислительной техникой, среди которых аппаратная платформа компьютеров, серверов, вычислительных машин, комплексов, систем и сетей; операционные системы и системное программное обеспечение; автоматизированные информационно-аналитические и управляющие системы, все виды обеспечивающих подсистем."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.01"],
        "profiles": ["Квантовые коммуникации и вычисления", "Цифровые комплексы, системы и сети", "Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "09-03-03-1": {
        "sectorTitle": "09.03.03 | Прикладная информатика",
        "sectorDescription": ["В рамках направления ведётся подготовка квалифицированных профессионалов в сферах системного анализа прикладной области информатизации и цифровизации; формализации решения прикладных задач и процессов информационных систем."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.03"],
        "profiles": ["Управление данными", "Цифровая трансформация", "Информатизация организаций"],
        "vacancies": null,
        "url": null
    },
    "09-03-04-1": {
        "sectorTitle": "09.03.04 | Программная инженерия",
        "sectorDescription": ["В рамках направления ведётся подготовка профессионалов в широком спектре технологий индустриального производства программного обеспечения для информационно-вычислительных систем различного назначения, в том числе в сферах применения современных методов и технологий проектирования, а также стандартов, регламентирующих жизненный цикл ПО."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Информационные технологии в атомной отрасли", "Разработка и дизайн компьютерных игр и мультимедийных приложений", "Проектирование и разработка сред и приложений дополненной и виртуальной реальностей", "Интеллектуальные системы поддержки принятия решений", "Системная и программная инженерия", "Информационные системы управления ресурсами предприятия"],
        "vacancies": null,
        "url": null
    },
    "09-03-04-2": {
        "sectorTitle": "09.03.04 | Программная инженерия",
        "sectorDescription": ["В рамках направления ведётся подготовка профессионалов в широком спектре технологий индустриального производства программного обеспечения для информационно-вычислительных систем различного назначения, в том числе в сферах применения современных методов и технологий проектирования, а также стандартов, регламентирующих жизненный цикл ПО."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Информационные технологии в атомной отрасли", "Разработка и дизайн компьютерных игр и мультимедийных приложений", "Проектирование и разработка сред и приложений дополненной и виртуальной реальностей", "Интеллектуальные системы поддержки принятия решений", "Системная и программная инженерия", "Информационные системы управления ресурсами предприятия"],
        "vacancies": null,
        "url": null
    },
    "additional-programm": {
        "sectorTitle": "Дополнительное образование",
        "sectorDescription": ["В рамках направления ведётся подготовка специалистов в области построения и администрирования средств защиты информации автоматизированных систем, организации технологий комплексной защиты информации.", "В ИИТ проводится обучение только в рамках дополнительных курсов на некоторых профилях, например на профиле \"Информационные технологии в атомной отрасли\", направления 09.03.04 Программная инженерия."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["Дополнительное образование", "09.03.04"],
        "profiles": ["Информационные технологии в атомной отрасли"],
        "vacancies": null,
        "url": null
    },
    "automation": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-1-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Стажёр',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-2-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Младший инженер',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-3-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Автоматизация и роботизация бизнес-процессов',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-3-2": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Сборка и тестирование',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-3-3": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Развёртывание и эксплуатация',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-3-4": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Мониторинг и безопасность',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-4-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Руководитель группы',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-5-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Руководитель департамента автоматизации',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data-1-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Стажёр аналитик",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data-2-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Аналитик данных",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data-2-2": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Инженер данных",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data-2-3": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Методолог данных",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data-3-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы аналитиков",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data-4-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Директор по данным",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-1-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Стажёр разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-2-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Младший разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-3-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-4-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Ведущий разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-5-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-5-2": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Архитектор",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-6-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента разработки",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "director": {
        "sectorTitle": "Руководящие должности",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-1-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Операционная поддержка пользователей",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-2": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Платформы виртуализации",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-3": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Системы хранения данных",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-4": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Серверные платформы",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-3-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Архитектор ИТ Инфраструктуры",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-3-2": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Инженер программист ПЛИС",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-3-3": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы ИТ Инфраструктуры",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-4-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента ИТ Инфраструктуры",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-1-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-2-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Внедрение моделей в прикладную отрасль",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-2-2": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Разработка данных и обучение",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-2-3": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Разработка моделей",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-3-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Ведущий разработчик систем искусственного интеллекта",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-4-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента искусственного интеллекта",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-1-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Технический писатель",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-2-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Бизнес аналитик",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-2-2": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Системный аналитик",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-3-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Руководитель проекта",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-4-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Руководитель портфеля проектов",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-5-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Руководитель проектного офиса",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "methodology-1": {
        "sectorTitle": "Гибкие методологии разработки",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-1-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-2-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Квантовые вычисления",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-2-2": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Квантовая коммуникация",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-3-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Инженер по разработке решений",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-3-2": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Эксперт по эксплуатации",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-4-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента квантовых технологий",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-1-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-2-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Тестирование на проникновение",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-2-2": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Управление информационной безопасностью",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-2-3": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Центр обеспечения безопасности",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-3-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы по обеспечению информационной безопасности",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-4-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента по информационной безопасности",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-1-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-2-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Оборудование",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-2-2": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Программное обеспечение",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-2-3": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Средства защиты информации",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-3-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-4-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента телекоммуникации",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    }
}

export default data;