export type dataObjectType = {
    sectorTitle: string,
    sectorDescription: string[],
    jobTitle: string | null,
    jobDescription: string[] | null,
    jobColor: string | null,
    directions: string[] | null,
    profiles: string[] | null,
    vacancies: string | null,
    url: string | null,
}
export type dataType = Record<string, dataObjectType>

const data: dataType = {
    "01-03-04-1": {
        "sectorTitle": "01.03.04 | Прикладная математика",
        "sectorDescription": ["Направление для тех, кто умеет мыслить строго и хочет применять математику к реальным задачам: анализ данных, моделирование, оптимизация и предиктивная аналитика. Сильная теоретическая база сочетается с практической инженерией данных."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["01.03.04"],
        "profiles": ["Анализ данных"],
        "vacancies": null,
        "url": null
    },
    "09-03-01-1": {
        "sectorTitle": "09.03.01 | Информатика и вычислительная техника",
        "sectorDescription": ["Направление про устройство и эксплуатацию вычислительных систем — от аппаратной архитектуры и низкоуровневого программирования до сетей, современной ИТ-инфраструктуры и квантовых технологий. Для тех, кто хочет понимать, как работает техника изнутри."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.01"],
        "profiles": ["Квантовые коммуникации и вычисления", "Цифровые комплексы, системы и сети", "Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "09-03-03-1": {
        "sectorTitle": "09.03.03 | Прикладная информатика",
        "sectorDescription": ["Направление на стыке ИТ и бизнеса: студенты понимают ИТ изнутри — технологии, архитектуры, паттерны и инструменты проектирования систем и ПО — и применяют эти знания в реальных организациях. Учатся внедрять и автоматизировать бизнес-процессы, управлять проектами и командами, а также информатизировать организации или трансформировать отдельные процессы с помощью цифровых технологий."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.03"],
        "profiles": ["Управление данными", "Цифровая трансформация", "Информатизация организаций"],
        "vacancies": null,
        "url": null
    },
    "09-03-04-1": {
        "sectorTitle": "09.03.04 | Программная инженерия",
        "sectorDescription": ["Направление для тех, кто хочет создавать программные продукты — от мобильных приложений и веб-сервисов до игр, AR/VR-сред, систем искусственного интеллекта и корпоративных решений. Студенты получают как инженерную базу разработки ПО, так и глубокую специализацию в выбранной области."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Информационные технологии в атомной отрасли", "Разработка и дизайн компьютерных игр и мультимедийных приложений", "Проектирование и разработка сред и приложений дополненной и виртуальной реальностей", "Интеллектуальные системы поддержки принятия решений", "Системная и программная инженерия", "Информационные системы управления ресурсами предприятия"],
        "vacancies": null,
        "url": null
    },
    "09-03-04-2": {
        "sectorTitle": "09.03.04 | Программная инженерия",
        "sectorDescription": ["Направление для тех, кто хочет создавать программные продукты — от мобильных приложений и веб-сервисов до игр, AR/VR-сред, систем искусственного интеллекта и корпоративных решений. Студенты получают как инженерную базу разработки ПО, так и глубокую специализацию в выбранной области."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Информационные технологии в атомной отрасли", "Разработка и дизайн компьютерных игр и мультимедийных приложений", "Проектирование и разработка сред и приложений дополненной и виртуальной реальностей", "Интеллектуальные системы поддержки принятия решений", "Системная и программная инженерия", "Информационные системы управления ресурсами предприятия"],
        "vacancies": null,
        "url": null
    },
    "additional-programm": {
        "sectorTitle": "Дополнительное образование",
        "sectorDescription": ["Дополнительные курсы, доступные студентам всех профилей, среди которых, например: Мобильная разработка на Kotlin от IT Академии Samsung; Разработка видеоигр на Unreal Engine 5; NLP и LLM инженерия на Python; Дизайн цифровых продуктов и интерфейсов в Figma; Проектирование и разработка хранилищ данных с применением Yandex Database.", "Помимо этого, для студентов отдельных профилей предусмотрены специализированные факультативные дисциплины — например, для профиля Информационные технологии в атомной отрасли (09.03.04) это информационная безопасность, криптография, защищённые системы и анализ уязвимостей."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["Дополнительное образование", "09.03.04"],
        "profiles": ["Информационные технологии в атомной отрасли"],
        "vacancies": null,
        "url": null
    },
    "automation": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": ["Перевод ручных и повторяющихся процессов в автоматический режим с помощью программных инструментов. Специалисты настраивают пайплайны сборки и тестирования, развёртывания и эксплуатации, мониторинга систем, а также роботизируют бизнес-процессы организаций."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.01", "09.03.03", "09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Системная и программная инженерия", "Информационные технологии в атомной отрасли", "Цифровая трансформация", "Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "automation-1-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Стажёр',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": ["09.03.01", "09.03.03", "09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Системная и программная инженерия", "Информационные технологии в атомной отрасли", "Цифровая трансформация", "Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "automation-2-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Младший инженер',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": ["09.03.01", "09.03.03", "09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Системная и программная инженерия", "Информационные технологии в атомной отрасли", "Цифровая трансформация", "Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "automation-3-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Автоматизация и роботизация бизнес-процессов',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": ["09.03.03", "09.03.04"],
        "profiles": ["Информационные технологии в атомной отрасли", "Цифровая трансформация"],
        "vacancies": null,
        "url": null
    },
    "automation-3-2": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Сборка и тестирование',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": ["09.03.04"],
        "profiles": ["Системная и программная инженерия"],
        "vacancies": null,
        "url": null
    },
    "automation-3-3": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Развёртывание и эксплуатация',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": ["09.03.01", "09.03.04"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Системная и программная инженерия", "Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "automation-3-4": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Мониторинг и безопасность',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": ["09.03.01"],
        "profiles": ["Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "automation-4-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Руководитель группы',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "automation-5-1": {
        "sectorTitle": "Автоматизация",
        "sectorDescription": [],
        "jobTitle": 'Руководитель департамента автоматизации',
        "jobDescription": [],
        "jobColor": "#FFC39B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": ["Извлечение смысла из данных для принятия верных решений. Специалисты собирают, обрабатывают и анализируют данные, строят модели и прогнозы, проектируют хранилища и потоки данных, формируют аналитические отчёты."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["01.03.04", "09.03.03"],
        "profiles": ["Анализ данных", "Управление данными"],
        "vacancies": null,
        "url": null
    },
    "data-1-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Стажёр аналитик",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": ["01.03.04", "09.03.03"],
        "profiles": ["Анализ данных", "Управление данными"],
        "vacancies": null,
        "url": null
    },
    "data-2-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Аналитик данных",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": ["01.03.04", "09.03.03"],
        "profiles": ["Анализ данных", "Управление данными"],
        "vacancies": null,
        "url": null
    },
    "data-2-2": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Инженер данных",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": ["01.03.04", "09.03.03"],
        "profiles": ["Анализ данных", "Управление данными"],
        "vacancies": null,
        "url": null
    },
    "data-2-3": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Методолог данных",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": ["01.03.04", "09.03.03"],
        "profiles": ["Анализ данных", "Управление данными"],
        "vacancies": null,
        "url": null
    },
    "data-3-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы аналитиков",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "data-4-1": {
        "sectorTitle": "Анализ данных",
        "sectorDescription": [],
        "jobTitle": "Директор по данным",
        "jobDescription": [],
        "jobColor": "#B9FF9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development": {
        "sectorTitle": "Разработка",
        "sectorDescription": ["Создание программных продуктов — от написания кода до проектирования архитектуры. Разработчики проектируют, реализуют и поддерживают приложения: мобильные, веб, десктопные, игры и корпоративные системы. Чем выше уровень — тем больше ответственности за архитектурные решения и команду."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.04", "09.03.01"],
        "profiles": ["Разработка программных продуктов и проектирование информационных систем", "Информационные технологии в атомной отрасли", "Разработка и дизайн компьютерных игр и мультимедийных приложений", "Проектирование и разработка сред и приложений дополненной и виртуальной реальностей", "Интеллектуальные системы поддержки принятия решений", "Системная и программная инженерия", "Информационные системы управления ресурсами предприятия", "Цифровые комплексы, системы и сети"],
        "vacancies": null,
        "url": null
    },
    "development-1-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Стажёр разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-2-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Младший разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-3-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-4-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Ведущий разработчик",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-5-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-5-2": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Архитектор",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "development-6-1": {
        "sectorTitle": "Разработка",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента разработки",
        "jobDescription": [],
        "jobColor": "#FEB9B9",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "director": {
        "sectorTitle": "Руководящие должности",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": ["Проектирование и эксплуатация технической основы любой организации: серверы, системы хранения данных, платформы виртуализации, сети. Специалисты обеспечивают надёжную, масштабируемую и управляемую среду для работы всех цифровых сервисов."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.01", "09.03.04"],
        "profiles": ["Инфраструктура информационных технологий", "Квантовые коммуникации и вычисления", "Информационные технологии в атомной отрасли"],
        "vacancies": null,
        "url": null
    },
    "infrastructure-1-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Операционная поддержка пользователей",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-2": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Платформы виртуализации",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-3": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Системы хранения данных",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-2-4": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Серверные платформы",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-3-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Архитектор ИТ Инфраструктуры",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-3-2": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Инженер программист ПЛИС",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-3-3": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы ИТ Инфраструктуры",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "infrastructure-4-1": {
        "sectorTitle": "ИТ Инфраструктура",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента ИТ Инфраструктуры",
        "jobDescription": [],
        "jobColor": "#8DB3FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": ["Разработка и применение моделей машинного обучения и нейронных сетей для решения прикладных задач. Специалисты занимаются разметкой данных, обучением моделей, их внедрением в продукты и разработкой новых архитектур."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.04", "01.03.04", "09.03.03"],
        "profiles": ["Интеллектуальные системы поддержки принятия решений", "Анализ данных", "Управление данными"],
        "vacancies": null,
        "url": null
    },
    "intelligence-1-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-2-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Внедрение моделей в прикладную отрасль",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-2-2": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Разработка данных и обучение",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-2-3": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Разработка моделей",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-3-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Ведущий разработчик систем искусственного интеллекта",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "intelligence-4-1": {
        "sectorTitle": "Искусственный интеллект",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента искусственного интеллекта",
        "jobDescription": [],
        "jobColor": "#9BFFB4",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": ["Организация процессов разработки и внедрения ИТ-продуктов. Специалисты понимают ИТ изнутри — технологии, архитектуры, паттерны и инструменты — и разбираются в бизнес-процессах организаций, что позволяет им грамотно ставить задачи команде и обеспечивать создание качественного продукта. Выявляют и формализуют требования, выстраивают коммуникацию между бизнесом и командой, управляют проектами и портфелями, обеспечивая достижение целей в срок и в рамках бюджета."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.03"],
        "profiles": ["Цифровая трансформация", "Информатизация организаций", "Управление данными"],
        "vacancies": null,
        "url": null
    },
    "management-1-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Технический писатель",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-2-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Бизнес аналитик",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-2-2": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Системный аналитик",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-3-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Руководитель проекта",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-4-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Руководитель портфеля проектов",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "management-5-1": {
        "sectorTitle": "Управление проектами",
        "sectorDescription": [],
        "jobTitle": "Руководитель проектного офиса",
        "jobDescription": [],
        "jobColor": "#FFEE9B",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "methodology-1": {
        "sectorTitle": "Гибкие методологии разработки",
        "sectorDescription": [],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": ["Одна из самых передовых областей современных технологий — на стыке квантовой физики и информатики. Специалисты работают с квантовыми вычислениями и квантовыми коммуникациями, проектируют квантовые сети и разрабатывают решения на их основе."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.01"],
        "profiles": ["Квантовые коммуникации и вычисления"],
        "vacancies": null,
        "url": null
    },
    "quantum-1-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-2-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Квантовые вычисления",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-2-2": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Квантовая коммуникация",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-3-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Инженер по разработке решений",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-3-2": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Эксперт по эксплуатации",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "quantum-4-1": {
        "sectorTitle": "Квантовые информационные технологии",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента квантовых технологий",
        "jobDescription": [],
        "jobColor": "#A173FF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": ["Защита данных, систем и инфраструктуры от угроз и атак. Специалисты проводят тестирование на проникновение, выстраивают процессы управления безопасностью и работают в центрах обеспечения безопасности (SOC)."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.04", "09.03.01"],
        "profiles": ["Информационные технологии в атомной отрасли", "Квантовые коммуникации и вычисления", "Инфраструктура информационных технологий"],
        "vacancies": null,
        "url": null
    },
    "security-1-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-2-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Тестирование на проникновение",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-2-2": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Управление информационной безопасностью",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-2-3": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Центр обеспечения безопасности",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-3-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы по обеспечению информационной безопасности",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "security-4-1": {
        "sectorTitle": "Информационная безопасность",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента по информационной безопасности",
        "jobDescription": [],
        "jobColor": "#8EFFD6",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": ["Проектирование и эксплуатация систем передачи данных и связи. Специалисты работают с аппаратным оборудованием, программным обеспечением сетей и средствами защиты информации в телекоммуникационных системах."],
        "jobTitle": null,
        "jobDescription": null,
        "jobColor": null,
        "directions": ["09.03.01"],
        "profiles": ["Цифровые комплексы, системы и сети"],
        "vacancies": null,
        "url": null
    },
    "telecommunications-1-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Стажёр",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-2-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Оборудование",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-2-2": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Программное обеспечение",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-2-3": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Средства защиты информации",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-3-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Руководитель группы",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    },
    "telecommunications-4-1": {
        "sectorTitle": "Телекоммуникации",
        "sectorDescription": [],
        "jobTitle": "Руководитель департамента телекоммуникации",
        "jobDescription": [],
        "jobColor": "#949BFF",
        "directions": null,
        "profiles": null,
        "vacancies": null,
        "url": null
    }
}

export default data;